package com.dedhapp3n.pokeldn.ldn

enum class LdnApTestPhase(val label: String) {
    DISCONNECTED("Disconnected"),
    READY("Ready"),
    PREPARING("Preparing"),
    STARTING_AP("Starting AP"),
    ADVERTISING("Advertising"),
    CONSOLE_ACTIVITY("Console activity detected"),
    AUTH_REQUEST("Authentication request received"),
    AUTH_RESPONSE_SENT("Authentication response sent"),
    AUTHENTICATION_REJECTED("Authentication rejected"),
    PARTICIPANT_REGISTERED("Participant registered"),
    STATION_ASSOCIATED("Station associated"),
    PIA_REQUEST("PIA connection request received"),
    PIA_RESPONSE_SENT("PIA response sent"),
    PIA_ESTABLISHED("PIA session established"),
    RELIABLE_ESTABLISHED("Reliable established"),
    PIA_FAILED("PIA session failed"),
    STOPPING("Stopping"),
    FAILED("Failed"),
    CLEANUP_REQUIRED("Cleanup required"),
}

data class LdnApTestState(
    val phase: LdnApTestPhase = LdnApTestPhase.DISCONNECTED,
    val detail: String? = null,
    val channel: Int? = null,
    val advertisementsSent: Long = 0,
    val discoveryActivityCount: Long = 0,
    val stationDetected: Boolean = false,
    val authenticationRequests: Long = 0,
    val authenticationResponses: Long = 0,
    val authenticationFailures: Long = 0,
    val participantRegistered: Boolean = false,
    val piaNetRequests: Long = 0,
    val piaSessionRequests: Long = 0,
    val piaSessionResponses: Long = 0,
    val piaEstablished: Boolean = false,
    val reliableEstablished: Boolean = false,
    val reliableFramesReceived: Long = 0,
    val reliableFramesSent: Long = 0,
    val latestActivity: String? = null,
)
